"""narration_cache table

Revision ID: c104f8c6d28d
Revises: d98e69ca1b67
Create Date: 2026-05-14 11:29:10.559690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c104f8c6d28d'
down_revision: Union[str, Sequence[str], None] = 'd98e69ca1b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narration_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('signals_hash', sa.Text(), nullable=False),
    sa.Column('narration_text', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'metric_date', 'signals_hash', name='uq_narration_cache_user_date_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('narration_cache')
    # ### end Alembic commands ###
