"""initial schema

Revision ID: d98e69ca1b67
Revises: 
Create Date: 2026-05-13 14:25:46.301611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd98e69ca1b67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('oura_sleep_score', sa.Integer(), nullable=True),
    sa.Column('oura_sleep_duration_min', sa.Integer(), nullable=True),
    sa.Column('oura_sleep_efficiency', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('oura_sleep_latency_min', sa.Integer(), nullable=True),
    sa.Column('oura_rem_min', sa.Integer(), nullable=True),
    sa.Column('oura_deep_min', sa.Integer(), nullable=True),
    sa.Column('oura_light_min', sa.Integer(), nullable=True),
    sa.Column('oura_awake_min', sa.Integer(), nullable=True),
    sa.Column('oura_hrv_avg', sa.Integer(), nullable=True),
    sa.Column('oura_rhr', sa.Integer(), nullable=True),
    sa.Column('oura_temp_deviation', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('oura_readiness_score', sa.Integer(), nullable=True),
    sa.Column('oura_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('whoop_recovery_score', sa.Integer(), nullable=True),
    sa.Column('whoop_hrv_ms', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('whoop_rhr', sa.Integer(), nullable=True),
    sa.Column('whoop_sleep_performance', sa.Integer(), nullable=True),
    sa.Column('whoop_sleep_need_min', sa.Integer(), nullable=True),
    sa.Column('whoop_sleep_debt_min', sa.Integer(), nullable=True),
    sa.Column('whoop_day_strain', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('whoop_avg_hr', sa.Integer(), nullable=True),
    sa.Column('whoop_max_hr', sa.Integer(), nullable=True),
    sa.Column('whoop_kcal_burned', sa.Integer(), nullable=True),
    sa.Column('whoop_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unified_hrv_z', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('unified_rhr_z', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('unified_sleep_z', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ingestion_complete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('oura_status', sa.Text(), nullable=True),
    sa.Column('whoop_status', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'metric_date', name='uq_daily_metrics_user_date')
    )
    op.create_index('idx_daily_metrics_user_date', 'daily_metrics', ['user_id', 'metric_date'], unique=False)
    op.create_table('manual_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('weight_lbs', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('kcal_consumed', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Integer(), nullable=True),
    sa.Column('fat_g', sa.Integer(), nullable=True),
    sa.Column('carbs_g', sa.Integer(), nullable=True),
    sa.Column('subjective_energy', sa.Integer(), nullable=True),
    sa.Column('subjective_mood', sa.Integer(), nullable=True),
    sa.Column('subjective_hunger', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_manual_log_user_date')
    )
    op.create_table('oauth_state',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'user_id', name='uq_oauth_state_provider_user')
    )
    op.create_table('regulation_recommendations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('rec_date', sa.Date(), nullable=False),
    sa.Column('rec_type', sa.Text(), nullable=True),
    sa.Column('suggested_kcal', sa.Integer(), nullable=True),
    sa.Column('suggested_training_mod', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('triggering_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reg_rec_user_date', 'regulation_recommendations', ['user_id', 'rec_date'], unique=False)
    op.create_table('workouts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('workout_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('workout_type', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('strain', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('kcal', sa.Integer(), nullable=True),
    sa.Column('zone_0_min', sa.Integer(), nullable=True),
    sa.Column('zone_1_min', sa.Integer(), nullable=True),
    sa.Column('zone_2_min', sa.Integer(), nullable=True),
    sa.Column('zone_3_min', sa.Integer(), nullable=True),
    sa.Column('zone_4_min', sa.Integer(), nullable=True),
    sa.Column('zone_5_min', sa.Integer(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_workouts_source_sourceid')
    )
    op.create_index('idx_workouts_type', 'workouts', ['workout_type'], unique=False)
    op.create_index('idx_workouts_user_date', 'workouts', ['user_id', 'workout_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workouts_user_date', table_name='workouts')
    op.drop_index('idx_workouts_type', table_name='workouts')
    op.drop_table('workouts')
    op.drop_index('idx_reg_rec_user_date', table_name='regulation_recommendations')
    op.drop_table('regulation_recommendations')
    op.drop_table('oauth_state')
    op.drop_table('manual_log')
    op.drop_index('idx_daily_metrics_user_date', table_name='daily_metrics')
    op.drop_table('daily_metrics')
    # ### end Alembic commands ###
